services:
  - type: web
    name: laravel
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: php artisan serve --host=0.0.0.0 --port=8000
    envVars:
      - key: APP_NAME
        value: SanhuaAutoParts
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: laravel-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: laravel-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-db
          property: password
    healthCheckPath: /
    buildCommand: composer install --no-interaction --no-dev --optimize-autoloader
    startCommand: |
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
      php artisan db:seed --force
      php artisan serve --host=0.0.0.0 --port=8000

databases:
  - name: laravel-db
    ipAllowList: []
    plan: free